superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_project/superheroes/urls.py
from django.urls import path

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('update/<int:hero_id>/', views.update, name='update'),
    path('delete/<int:hero_id>/', views.delete, name='delete')
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=150)

    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":        
        #save the form as new database contents
        #return to index
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def update(request, hero_id): 
    updated_hero = Superhero.objects.get(pk=hero_id)
    if request.method == "POST":
        updated_hero.name = request.POST.get('name')
        updated_hero.alter_ego = request.POST.get('alter_ego')
        updated_hero.primary = request.POST.get('primary')
        updated_hero.secondary = request.POST.get('secondary')
        updated_hero.catchphrase = request.POST.get('catchphrase')
        updated_hero.save()
        return HttpResponseRedirect(reverse('superheroes:update'))
    else:
        context = {
            'single_hero': updated_hero
        }
        return render(request, 'superheroes/update.html', context)

def delete(request, hero_id):
    hero = Superhero.objects.get(pk=hero_id)
    hero.delete()
    return HttpResponseRedirect(reverse('superheroes:index'))

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add!">
    </form>
    <a href="{% url 'superheroes:index' %}">Return to Home Page</a>
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Detail</title>
</head>
<body>
    <h1>Details about Superhero</h1>
    <ul>        
        <li><h2>Superhero: {{single_hero.name}}</h2></li>
        <li>Alter Ego: {{single_hero.alter_ego}}</li>
        <li>Primary Ability: {{single_hero.primary_ability}}</li>
        <li>Secondary Ability: {{single_hero.secondary_ability}}</li>
        <li>Catchphrase: {{single_hero.catch_phrase}}</li>        
    </ul>    
    <a href="{% url 'superheroes:delete' single_hero.id %}">Delete this Hero</a> <br> 
    <a href="{% url 'superheroes:update' single_hero.id %}">Update this Heroes Information</a> <br> 
    <a href="{% url 'superheroes:index' %}">Return to Home Page</a> <br>
    <a href="{% url 'superheroes:create' %}">Add New Hero</a>
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Heroes</h1>
    <ul>
        {% for hero in all_heroes %}
        <li><h2>{{hero.name}} - <a href="{% url 'superheroes:detail' hero.id %}">Click for details</a></h2></li>
        {% endfor %}
    </ul>
    <a href="{% url 'superheroes:create' %}">Add New Hero</a>
</body>
</html>

superhero_project/superheroes/templates/superheroes/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Hero Information</title>
</head>
<body>    
    </ul>
    <h1>Please change one or more fields below to update hero details</h1>
    <form action="{% url 'superheroes:update' single_hero.id %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name" value={{single_hero.name}}><br />        
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego" value={{single_hero.alter_ego}}><br />         
        Primary Ability: <input type="text" name="primary" id="primary" value={{single_hero.primary_ability}}><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary" value={{single_hero.secondary_ability}}><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase" value={{single_hero.catch_phrase}}><br />
        <input type="submit" value="Update!">
    </form>
    <a href="{% url 'superheroes:index' %}">Return to Home Page</a> <br>
</body>
</html>